apiVersion: core.openfeature.dev/v1alpha3
kind: FlagSourceConfiguration
metadata:
    name: source-configuration
spec:
    metricsPort: 8080
    Port: 80
    evaluator: json
    defaultSyncProvider: filepath
    tag: main
    sources:
    - source: open-feature-demo/end-to-end
      provider: kubernetes
    probesEnabled: true
---
apiVersion: core.openfeature.dev/v1alpha2
kind: FeatureFlagConfiguration
metadata:
  name: end-to-end
  namespace: open-feature-demo
spec:
  featureFlagSpec:
    flags:
      new-welcome-message:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'off'
      hex-color:
        variants:
          red: c05543
          green: 2f5230
          blue: 0d507b
        defaultVariant: blue
        state: ENABLED
      fib-algo:
        variants:
          recursive: recursive
          memo: memo
          loop: loop
          binet: binet
        defaultVariant: recursive
        state: ENABLED
        targeting: {
          "if": [
            {
              "in": ["@faas.com", {
                "var": ["email"]
              }]
            }, "binet", null
          ]
        }
