apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-jaeger-agent
  namespace: open-feature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo-jaeger
  template:
    metadata:
      labels:
        app: open-feature-demo-jaeger
    spec:
      containers:
        - name: open-feature-demo-jaeger
          image: jaegertracing/all-in-one:1.38
          env:
            - name: QUERY_BASE_PATH
              value: /tracing
          ports:
            - containerPort: 6832
            - containerPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-jaeger-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo-jaeger
  ports:
    - port: 6832
      targetPort: 6832
      name: internal
      protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-jaeger-ui
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo-jaeger
  ports:
    - port: 80
      targetPort: 16686

