apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-playground-app
  namespace: open-feature-demo
  labels:
    app: open-feature-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo
  template:
    metadata:
      labels:
        app: open-feature-demo
      annotations:
        openfeature.dev: "enabled"
        openfeature.dev/featureflagconfiguration: "end-to-end"
    spec:
      volumes:
        - name: proxy-config
          configMap:
            name: proxy-config
            items:
              - key: nginx.conf
                path: nginx.conf
      containers:
        - name: flagd-proxy
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: proxy-config
              mountPath: /etc/nginx
              readOnly: true
        - name: open-feature-demo
          image: ghcr.io/open-feature/playground-app:v0.8.0
          args:
            - flagd
          ports:
            - containerPort: 30000
          envFrom:
            - configMapRef:
                name: open-feature-demo-config
            - configMapRef:
                name: open-feature-demo-env-flag-config
          env:
            - name: HARNESS_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: harness-keys
                  optional: true
            - name: LD_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: ld-key
                  optional: true
            - name: SPLIT_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: split-key
                  optional: true
            - name: CLOUDBEES_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: cloudbees-key
                  optional: true
            - name: FLAGSMITH_ENV_KEY
              valueFrom:
                secretKeyRef:
                  name: vendor-keys
                  key: flagsmith-key
                  optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo
  ports:
    - port: 80
      targetPort: 30000
---
apiVersion: v1
kind: Service
metadata:
  name: flagd-service
  namespace: open-feature-demo
spec:
  type: ClusterIP
  selector:
    app: open-feature-demo
  ports:
    - port: 80
      targetPort: 30000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open-feature-demo-config
  namespace: open-feature-demo
data:
  OTEL_EXPORTER_JAEGER_AGENT_HOST: open-feature-demo-jaeger-service
  OTEL_EXPORTER_JAEGER_AGENT_PORT: "6832"
  GO_FEATURE_FLAG_URL: http://open-feature-demo-goff-service:1031
  FIB_SERVICE_URL: http://open-feature-fibonacci-service:30002
  NODE_ENV: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        location / {
          proxy_pass http://127.0.0.1:8013;
        }
      }
    }

